spring:
  application:
    name: csa-auth-service

server:
  port: 26001

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true

logging:
  level:
    root: ERROR